# Generated by Django 2.1.1 on 2019-04-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schoocl',
            new_name='School',
        ),
    ]
