# Generated by Django 2.1.1 on 2019-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('generic', '0004_auto_20190426_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('realname', models.CharField(max_length=32, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')], verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete='cascade', to='generic.DepartMent', verbose_name='部门')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='所属角色')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
