# Generated by Django 2.1.1 on 2019-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_staffinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='课程名称')),
            ],
        ),
    ]
