# Generated by Django 2.1.1 on 2019-04-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0006_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(verbose_name='班级(期)')),
                ('price', models.PositiveIntegerField(verbose_name='学费')),
                ('start_date', models.DateField(verbose_name='开班时间')),
                ('graduate_date', models.DateField(blank=True, null=True, verbose_name='结业时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('class_teacher', models.ForeignKey(on_delete='cascade', related_name='classes', to='generic.Staffinfo', verbose_name='班主任')),
                ('course', models.ForeignKey(on_delete='cascade', to='generic.Course', verbose_name='课程')),
                ('school', models.ForeignKey(on_delete='cascade', to='generic.School', verbose_name='校区')),
                ('tech_teachers', models.ManyToManyField(blank=True, related_name='tech_classes', to='generic.Staffinfo', verbose_name='任课老师')),
            ],
        ),
    ]
