# Generated by Django 2.1.1 on 2019-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0009_consultrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.IntegerField(choices=[(1, '报名费'), (2, '学费'), (3, '退学'), (4, '其他')], default=1, verbose_name='费用类型')),
                ('paid_fee', models.IntegerField(default=0, verbose_name='金额')),
                ('apply_date', models.DateTimeField(auto_now_add=True, verbose_name='申请日期')),
                ('confirm_status', models.IntegerField(choices=[(1, '申请中'), (2, '已确认'), (3, '已驳回')], default=1, verbose_name='确认状态')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='确认日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('class_list', models.ForeignKey(on_delete='cascade', to='generic.Classes', verbose_name='申请班级')),
                ('confirm_user', models.ForeignKey(on_delete='cascade', related_name='confirms', to='generic.Staffinfo', verbose_name='审批人')),
                ('consultant', models.ForeignKey(help_text='谁签的单就选谁', on_delete='cascade', to='generic.Staffinfo', verbose_name='课程顾问')),
                ('customer', models.ForeignKey(on_delete='cascade', to='generic.Customer', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=32, verbose_name='QQ号')),
                ('mobile', models.CharField(max_length=32, verbose_name='手机号')),
                ('emergency_contract', models.CharField(max_length=32, verbose_name='紧急联系人电话')),
                ('student_status', models.IntegerField(choices=[(1, '申请中'), (2, '在读'), (3, '毕业'), (4, '退学')], default=1, verbose_name='学员状态')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('class_list', models.ManyToManyField(blank=True, to='generic.Classes', verbose_name='已报班级')),
                ('customer', models.OneToOneField(on_delete='cascade', to='generic.Customer', verbose_name='客户信息')),
            ],
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'depart__title__in': ['销售部', '运营部']}, on_delete='cascade', to='generic.Staffinfo', verbose_name='跟进人'),
        ),
    ]
