# Generated by Django 2.1.1 on 2019-04-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0010_auto_20190428_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrecord',
            old_name='class_list',
            new_name='classes',
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', related_name='confirms', to='generic.Staffinfo', verbose_name='审批人'),
        ),
    ]
